services:
  # 💾 1. Banco de Dados Postgres da ARSAL
  postgres-db:
    image: postgres:15-alpine
    container_name: arsal-postgres
    environment:
      POSTGRES_DB: tv_corporativa
      POSTGRES_USER: andre
      POSTGRES_PASSWORD: arsal@password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ☕ 2. Backend Spring Boot (Java)
  api-server:
    build: ./tv-corporativa-api  # 👈 Foca o Docker direto dentro da pasta do print!
    container_name: arsal-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/tv_corporativa
      - SPRING_DATASOURCE_USERNAME=andre
      - SPRING_DATASOURCE_PASSWORD=arsal@password
  # 📺 3. Frontend Angular (Nginx)
  web-tv:
    build:
      context: .
      dockerfile: ./tv-corporativa-frontend/Dockerfile
    container_name: arsal-front
    ports:
      - "80:80"
    depends_on:
      - api-server

# 📦 CORRIGIDO: Esta seção declara formalmente o volume para o Postgres não perder os dados
volumes:
  postgres_data: