services:
  # 💾 1. Banco de Dados Postgres da ARSAL
  postgres-db:
    image: postgres:15-alpine
    container_name: arsal-postgres
    environment:
      POSTGRES_DB: tv_corporativa
      POSTGRES_USER: andre
      POSTGRES_PASSWORD: arsal@password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 🪣 2. Servidor de Armazenamento de Objetos MinIO (NOVO!)
  minio:
    image: minio/minio
    container_name: arsal-minio
    ports:
      - "9000:9000"       # Porta da API (Onde o Java vai enviar os vídeos)
      - "9001:9001"       # Porta do Console Web (Para você gerenciar os arquivos pelo navegador)
    environment:
      MINIO_ROOT_USER: andreminio
      MINIO_ROOT_PASSWORD: arsalminiopassword
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  # ☕ 3. Backend Spring Boot (Java)
  api-server:
    build: ./tv-corporativa-api
    container_name: arsal-api
    ports:
      - "0.0.0.0:8085:8080"
    depends_on:
      - postgres-db
      - minio
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/tv_corporativa
      - SPRING_DATASOURCE_USERNAME=andre
      - SPRING_DATASOURCE_PASSWORD=arsal@password
      # 🎯 CONFIGURAÇÕES DO MINIO PARA O JAVA:
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=andreminio
      - MINIO_SECRET_KEY=arsalminiopassword
      - MINIO_BUCKET=tv-midias
    # ❌ REPAROU? NÃO PRECISA MAIS DO VOLUME C:/arsal_midias AQUI! 🎉

  # 🌐 4. Frontend Angular
  web-tv:
    build:
      context: .
      dockerfile: ./tv-corporativa-frontend/Dockerfile
    container_name: arsal-front
    ports:
      - "80:80"
    depends_on:
      - api-server

volumes:
  postgres_data:
  minio_data:       # Volume para o MinIO não perder os vídeos quando reiniciar