server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # 👇 Essencial para o Angular: se atualizar a página na rota /tv-loop, não dá erro 404!
        try_files $uri $uri/ /index.html;
    }
}